<?php
/**
 * Forms and commenting customization functions.
 *
 * @package Simple Grey
 */

/**
 * Completely removes the "Required fields are marked *" markup globally from the form,
 * preventing it from appending inside the logged-in paragraph wrapper.
 *
 * @param string $message The HTML markup containing the required fields notice.
 * @return string An empty string to hide the message completely.
 */
function simple_grey_remove_required_message_globally( $message ) {
	$message = '';

	return $message;
}
add_filter( 'wp_required_field_message', 'simple_grey_remove_required_message_globally' );

/**
 * Changes the default visual required field asterisk to a text indicator.
 *
 * @param string $indicator The HTML markup for the visual indicator.
 * @return string Modified HTML markup containing the new text indicator string.
 */
function simple_grey_change_required_indicator( $indicator ) {
	$indicator = '<span class="required"> ' . __( '(required)', 'simple-grey' ) . '</span>';
	return $indicator;
}
add_filter( 'wp_required_field_indicator', 'simple_grey_change_required_indicator' );

/**
 * Automatically loops through all form fields and appends "(optional)"
 * to the labels of any fields that do not contain a required attribute or flag.
 *
 * @param array $comment_fields Array of HTML strings for all comment form fields.
 * @return array The processed fields array with optional tags cleanly injected.
 */
function simple_grey_add_optional_to_labels( $comment_fields ) {
	foreach ( $comment_fields as $key => $field_html ) {
		// Skip adding (optional) if the field is explicitly marked as required.
		if ( strpos( $field_html, 'required=' ) !== false || strpos( $field_html, 'class="required"' ) !== false ) {
			continue;
		}

		// Locate the closing tag of the HTML label element.
		if ( strpos( $field_html, '</label>' ) !== false ) {
			$optional_markup = '<span class="optional"> ' . __( '(optional)', 'simple-grey' ) . '</span></label>';

			// Replace the original closing label tag with our custom text wrapper.
			$comment_fields[ $key ] = str_replace( '</label>', $optional_markup, $field_html );
		}
	}

	return $comment_fields;
}
add_filter( 'comment_form_fields', 'simple_grey_add_optional_to_labels', 30 );

/**
 * Dynamically appends an internationalized required label to the Core Search Block.
 *
 * Filters the content of the core/search block on render to include a localized
 * span indicating that the search field is required.
 *
 * @since 2.0.0
 *
 * @param string $block_content The block content to be rendered.
 * @param array  $block         The full block data, including name and attributes.
 * @return string The modified block content containing the updated label.
 */
function simple_grey_modify_search_block_label( $block_content, $block ) {

	// Check if it's the core search block.
	if ( 'core/search' === $block['blockName'] ) {

		$required_span = sprintf( '<span class="required">%s</span>', esc_html__( '(required)', 'simple-grey' ) );

		// Inject the span right before the closing </label> tag.
		$block_content = str_replace( '</label>', $required_span . '</label>', $block_content );
	}
	return $block_content;
}
add_filter( 'render_block', 'simple_grey_modify_search_block_label', 10, 2 );

/**
 * Appends an internationalized required label to classic search form templates.
 *
 * Filters the HTML output generated by get_search_form() to inject a localized
 * span inside the form's label tag.
 *
 * @since 2.0.0
 *
 * @param string $form The HTML content of the search form.
 * @return string The modified search form HTML with the updated label.
 */
function simple_grey_modify_get_search_form_label( $form ) {

	$required_span = sprintf( '<span class="required">%s</span>', esc_html__( '(required)', 'simple-grey' ) );

	// Inject the span right before the closing </label> tag.
	$form = str_replace( '</label>', $required_span . '</label>', $form );

	return $form;
}
add_filter( 'get_search_form', 'modify_get_search_form_label' );
